<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_galik1999</name>
   <tag></tag>
   <elementGuidId>9d5308f9-5b6b-4c6a-9937-f23d84276754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r5:']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Truncate__StyledTruncate-sc-23o1d2-0.fWcxCG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>99d042d7-ad15-4ccc-bc07-7244c9309be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>galik1999</value>
      <webElementGuid>bd7b5249-190a-4e57-842c-b79ea79bdfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Truncate__StyledTruncate-sc-23o1d2-0 fWcxCG</value>
      <webElementGuid>e378fa95-26e0-415d-a24c-f5c599a41f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>galik1999</value>
      <webElementGuid>c4dbc73a-0be9-4b1b-8cd9-fb3525019a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r5:&quot;)/div[@class=&quot;d-flex flex-1&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;lh-condensed overflow-hidden d-flex flex-column flex-justify-center ml-2 f5 mr-auto&quot;]/div[@class=&quot;text-bold&quot;]/div[@class=&quot;Truncate__StyledTruncate-sc-23o1d2-0 fWcxCG&quot;]</value>
      <webElementGuid>3bbbb273-6688-42d8-8b77-4aec601ce639</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r5:']/div/div/div/div/div</value>
      <webElementGuid>9f5a8df8-0612-45c8-b89b-ab02ba6acb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore more →'])[2]/following::div[15]</value>
      <webElementGuid>5652235a-f89b-4a1a-8cdf-ba1b1a0bb2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Galik'])[1]/preceding::div[1]</value>
      <webElementGuid>df3edd23-4c5f-40c3-88b1-dbf7350934e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set status'])[1]/preceding::div[3]</value>
      <webElementGuid>6fc5172b-a008-48b8-82fd-83b08e0ce998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>6eae9331-d79e-468a-bca6-70c484b97240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'galik1999' and (text() = 'galik1999' or . = 'galik1999')]</value>
      <webElementGuid>78dc0d7a-ad19-42d3-807d-517be6e65288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
