<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create new_avatar circle</name>
   <tag></tag>
   <elementGuidId>38a97fc8-5eea-4edc-b2f3-fbce2b479d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://avatars.githubusercontent.com/u/77876503?v=4')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.avatar.circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bab56adc-629b-4513-afdc-3d4d162457f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://avatars.githubusercontent.com/u/77876503?v=4</value>
      <webElementGuid>1c94c8e0-0f98-474b-ad0c-1a40825f1f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>5622c5e9-9e32-42c0-baf7-a1c70ee4765f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>ddbc3e75-7961-4bcf-adde-1fe1c9fafb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>2ccb8661-49e6-465d-bb54-4a54728bc643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view-component</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc7f1ebb-be31-4d41-8171-b1373108ca06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar circle</value>
      <webElementGuid>0500273b-8e41-42b7-9e2c-107d209960e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;logged-in env-production page-responsive full-width&quot;]/div[@class=&quot;logged-in env-production page-responsive full-width&quot;]/div[@class=&quot;position-relative js-header-wrapper&quot;]/header[@class=&quot;AppHeader&quot;]/div[@class=&quot;AppHeader-globalBar  js-global-bar&quot;]/div[@class=&quot;AppHeader-globalBar-end&quot;]/div[@class=&quot;AppHeader-user&quot;]/deferred-side-panel[1]/include-fragment[1]/react-partial-anchor[1]/button[@class=&quot;Button--invisible Button--medium Button Button--invisible-noVisuals color-bg-transparent p-0&quot;]/span[@class=&quot;Button-content&quot;]/span[@class=&quot;Button-label&quot;]/img[@class=&quot;avatar circle&quot;]</value>
      <webElementGuid>cc74d828-8d75-49fd-91c1-310b2a01c413</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://avatars.githubusercontent.com/u/77876503?v=4')]</value>
      <webElementGuid>5acdbeaa-c319-4a62-99e4-1e5e67a19d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>418f1e5f-ef21-4403-9c21-3d3c6db378ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://avatars.githubusercontent.com/u/77876503?v=4']</value>
      <webElementGuid>171d9170-24ff-47f7-8f2e-aa436992c04d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
