<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_image_big</name>
   <tag></tag>
   <elementGuidId>98c4dfd6-9d5b-481f-a10a-ffe64459a824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://avatars.githubusercontent.com/u/77876503?v=4']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='upload-avatar-link']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.avatar.avatar-user.width-full.border.color-bg-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>df6cd188-9189-413c-90ff-cf418bdc2484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://avatars.githubusercontent.com/u/77876503?v=4</value>
      <webElementGuid>c2264f94-afc5-4127-973d-f5c686c3de4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>260</value>
      <webElementGuid>553866e0-916b-4af9-9881-04fe1ee98f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>260</value>
      <webElementGuid>0c09604b-9d54-4213-aabb-abdccd00562b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar avatar-user width-full border color-bg-default</value>
      <webElementGuid>880a3fd2-2317-4ab4-9f3c-a26f4c4ffbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload-avatar-link&quot;)/img[@class=&quot;avatar avatar-user width-full border color-bg-default&quot;]</value>
      <webElementGuid>cb569373-f821-495c-8d3a-823131f0a8b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='upload-avatar-link']/img</value>
      <webElementGuid>061c87a4-f1b9-4d30-9216-92b9f09e9a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://avatars.githubusercontent.com/u/77876503?v=4')])[2]</value>
      <webElementGuid>2ebd6795-e0ca-495a-a8d5-f9ce0e4d9cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>ca572328-edba-4527-884f-6e1c11c3eddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://avatars.githubusercontent.com/u/77876503?v=4']</value>
      <webElementGuid>be2508ea-882e-4d86-be8d-c504febe534f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
