<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Maze_Java</name>
   <tag></tag>
   <elementGuidId>3d8ecdbc-527a-4c22-ac30-a715211fb0e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='557350605']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.repo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d238a334-1664-41fe-9c30-0155e261dee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>repo</value>
      <webElementGuid>e6e2b30a-ccfe-4a01-8996-e9cecb5d8519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Maze_Java
              </value>
      <webElementGuid>6c7bb085-3d6a-4797-a54c-34c4bf749ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;557350605&quot;)/span[@class=&quot;repo&quot;]</value>
      <webElementGuid>5f812693-5e46-419c-9afb-98271e95b2ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='557350605']/span</value>
      <webElementGuid>d9b5d981-76a2-4aa2-899e-60c7d24fcb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[6]/following::span[3]</value>
      <webElementGuid>c879923d-a38e-432d-9cad-fea4f69dbefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maze_Java'])[2]/preceding::span[1]</value>
      <webElementGuid>63b4a3ac-1d0f-445b-9fe4-0d3db289e7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[1]/preceding::span[2]</value>
      <webElementGuid>2ac3a5ea-4433-45db-b59c-f0608a836876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maze_Java']/parent::*</value>
      <webElementGuid>a4805e5c-826b-4c09-9034-6b7bcb128df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/span</value>
      <webElementGuid>dc68b56a-8ac1-47df-86f2-672efea9df52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                Maze_Java
              ' or . = '
                Maze_Java
              ')]</value>
      <webElementGuid>60d0749a-d4fb-465a-bb44-787cd12e9a3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
