<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Node-JS-Repo</name>
   <tag></tag>
   <elementGuidId>3b82373e-cd91-4a90-87a8-798febe7fab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='631367316']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#631367316 > span.repo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cdfd707f-fc21-4d52-ac66-052398fbb424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>repo</value>
      <webElementGuid>b5a08d35-6dbd-4e28-be6f-39f6c827762c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Node-JS-Repo
              </value>
      <webElementGuid>571db2ba-823b-41f6-ade0-c23bd2e01936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;631367316&quot;)/span[@class=&quot;repo&quot;]</value>
      <webElementGuid>ae264b82-9c39-4d3f-bbb5-aa238d80e6f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='631367316']/span</value>
      <webElementGuid>02632fb0-0493-473f-84de-13f3d749de56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java'])[3]/following::span[2]</value>
      <webElementGuid>51df84e3-4f13-4116-9d85-8c41c130da51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[4]/following::span[5]</value>
      <webElementGuid>16c34e98-5953-4e48-9c0c-0125bc023a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Node-JS-Repo'])[2]/preceding::span[1]</value>
      <webElementGuid>247087ca-be74-40df-8538-f77c3d19e302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[5]/preceding::span[2]</value>
      <webElementGuid>6fc76c92-3af3-425c-b33e-0bcc94b8c5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Node-JS-Repo']/parent::*</value>
      <webElementGuid>da907e76-d6ff-41d5-8e46-5c3c32c306a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/div/span/a/span</value>
      <webElementGuid>03ab7913-c2be-41bc-a1f5-a1927daee4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                Node-JS-Repo
              ' or . = '
                Node-JS-Repo
              ')]</value>
      <webElementGuid>3fa2d3f2-0e92-43e8-a9e7-7f6105bf5cfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
