<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TicTacToe</name>
   <tag></tag>
   <elementGuidId>c786e9d5-b496-4fa6-a0a1-0a55811627bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='558943477']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#558943477 > span.repo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>214d6d6a-431c-4fb3-aae9-9a43a160b26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>repo</value>
      <webElementGuid>41fa098d-4413-4102-a719-1476dae12728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                TicTacToe
              </value>
      <webElementGuid>409682fc-b2d0-4c52-94b0-aee631118d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;558943477&quot;)/span[@class=&quot;repo&quot;]</value>
      <webElementGuid>bf6c6a93-9aa4-44eb-b68c-0372980326e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='558943477']/span</value>
      <webElementGuid>1b0ab95f-4af0-414e-9423-35382cc7b380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[3]/following::span[2]</value>
      <webElementGuid>387729d3-d9d4-4fdf-baf6-5288348c56a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restaurant_C_Linux'])[2]/following::span[5]</value>
      <webElementGuid>8e6e6e8c-f080-41c2-842b-d90e42e23496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TicTacToe'])[2]/preceding::span[1]</value>
      <webElementGuid>e4f5b640-d947-498f-a189-39879890267c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[4]/preceding::span[2]</value>
      <webElementGuid>3fed905f-9a62-4208-8d45-af4d687b5939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TicTacToe']/parent::*</value>
      <webElementGuid>273d46c8-96bb-4a5f-932d-a7b9230d771c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/div/span/a/span</value>
      <webElementGuid>796b7b59-862d-4a01-8f39-1e865c16508b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                TicTacToe
              ' or . = '
                TicTacToe
              ')]</value>
      <webElementGuid>75eda173-f317-4e72-9780-708b11dbd42f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
