<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Repositories</name>
   <tag></tag>
   <elementGuidId>c80b9c08-2fdf-4b4d-b58d-3a5d732c23cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='repositories-tab']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#repositories-tab > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4929653-4497-43e9-a9ec-9fb8e8477dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view-component</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fb6943c-c9ba-4357-bad8-3bbc9d302fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Repositories</value>
      <webElementGuid>d48b7a1f-5894-4980-aeef-33764bc3957d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repositories-tab&quot;)/span[1]</value>
      <webElementGuid>74e88f8a-43c3-4fc5-9517-25840acb2727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='repositories-tab']/span</value>
      <webElementGuid>2e49fe5c-5be2-4a65-951f-93d4a3801ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::span[2]</value>
      <webElementGuid>1fc510f3-122d-49af-af94-00beb0092b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create new...'])[1]/following::span[5]</value>
      <webElementGuid>f6f068cf-3425-4df4-8593-88b4398a84c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[2]/preceding::span[2]</value>
      <webElementGuid>aa456033-f832-4533-aaa0-9512e339cc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packages'])[1]/preceding::span[4]</value>
      <webElementGuid>bc543366-59ca-468e-adba-a1e3bf75b12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Repositories']/parent::*</value>
      <webElementGuid>2067b758-c7a6-4269-b8d1-7029500e3fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a/span</value>
      <webElementGuid>ae69a700-d616-4a8a-9fa0-f5343835495b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Repositories' or . = 'Repositories')]</value>
      <webElementGuid>bfee8252-169a-4e19-8993-7d19d8d05a17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
