<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cloud_Branch</name>
   <tag></tag>
   <elementGuidId>6a3003fd-05de-462a-9f30-d2e8588fc8ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='642583561']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#642583561 > span.repo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91f96ada-dea8-4a42-ab37-7247d6c872e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>repo</value>
      <webElementGuid>83f16388-7731-4c09-8cbc-bc5cbd0b0fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Cloud_Branch
              </value>
      <webElementGuid>d11048ad-f12b-47b0-94c5-71c656b14dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;642583561&quot;)/span[@class=&quot;repo&quot;]</value>
      <webElementGuid>612a27e4-2224-4054-ab0d-41448adcc3d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='642583561']/span</value>
      <webElementGuid>128f18c2-e47a-4ec2-91d8-d6900a6790cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript'])[1]/following::span[2]</value>
      <webElementGuid>dda212a6-cc88-42d1-980e-0e0a5311b027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[5]/following::span[5]</value>
      <webElementGuid>5e8e3504-c055-4587-bcc0-08f613c7b691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud_Branch'])[2]/preceding::span[1]</value>
      <webElementGuid>ad004ea5-3599-471a-9a69-6bf5e03cc873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[6]/preceding::span[2]</value>
      <webElementGuid>6ef99e33-6471-4f5b-b86c-2b9770529f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cloud_Branch']/parent::*</value>
      <webElementGuid>b28a3bc4-fd49-48fd-8f4f-3f23ca554706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div/div/span/a/span</value>
      <webElementGuid>d0e280bf-801c-465f-89a3-8b4f2a6a19cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                Cloud_Branch
              ' or . = '
                Cloud_Branch
              ')]</value>
      <webElementGuid>a1723a10-a75e-4fc0-89a5-734e387938df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
