<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Restaurant_C_Linux</name>
   <tag></tag>
   <elementGuidId>0c6f3798-077f-47ad-9787-75e539566baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='557358896']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#557358896 > span.repo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32880294-41c7-44e7-92f5-823d2f6e677c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>repo</value>
      <webElementGuid>78e96174-85aa-47a8-a0f4-6d07e1da2e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Restaurant_C_Linux
              </value>
      <webElementGuid>1b2ad41d-133f-46cd-84b1-2f385282ee0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;557358896&quot;)/span[@class=&quot;repo&quot;]</value>
      <webElementGuid>7a9f456d-4a56-4106-b243-02b39c944b16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='557358896']/span</value>
      <webElementGuid>0639d8af-1545-4ca4-8614-e9461c5b9879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java'])[2]/following::span[2]</value>
      <webElementGuid>91f1654e-7a13-483e-8739-66faeb25a7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[2]/following::span[5]</value>
      <webElementGuid>410c815e-b261-4273-8fae-c2f55bfedfa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restaurant_C_Linux'])[2]/preceding::span[1]</value>
      <webElementGuid>114308ed-4735-442a-94bd-0c428763d193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[3]/preceding::span[2]</value>
      <webElementGuid>019999f3-7d78-4b76-868b-b9d29f68fe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Restaurant_C_Linux']/parent::*</value>
      <webElementGuid>cb17a725-4976-4eb8-ad4c-fbbca8fc5f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/span/a/span</value>
      <webElementGuid>410f47db-3acf-47d7-9551-c2775beaab5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                Restaurant_C_Linux
              ' or . = '
                Restaurant_C_Linux
              ')]</value>
      <webElementGuid>14aebcd8-189a-4bd4-9f47-28ff17c228d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
