<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MinesSweeper_Java</name>
   <tag></tag>
   <elementGuidId>e251b1b4-161f-42a1-8319-6f9d0cacbd56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='557357201']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#557357201 > span.repo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5b9b262-10af-4d8c-8508-5bc678a4d26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>repo</value>
      <webElementGuid>3d009de2-f9b8-40b0-a982-024cfc26b56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                MinesSweeper_Java
              </value>
      <webElementGuid>4c3b5738-b07a-4959-a755-a450b706d018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;557357201&quot;)/span[@class=&quot;repo&quot;]</value>
      <webElementGuid>e3fe7e6b-8e0d-4ee1-9e05-0d2d077ba9cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='557357201']/span</value>
      <webElementGuid>60e5ee6c-18d8-4733-8da9-f2bf6fd150f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java'])[1]/following::span[2]</value>
      <webElementGuid>ba817bc8-bcf0-4f80-bf89-a053a523a725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[1]/following::span[5]</value>
      <webElementGuid>01ffbc53-e2bc-4357-9890-227d8d4769fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MinesSweeper_Java'])[2]/preceding::span[1]</value>
      <webElementGuid>9caa89f2-bc5c-4f4e-91ed-1c263d69d76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[2]/preceding::span[2]</value>
      <webElementGuid>eecd3dbf-58e2-40c9-a33d-3ff27d1a7a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MinesSweeper_Java']/parent::*</value>
      <webElementGuid>28c7c06a-77ab-44e8-8f0e-e979165339c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/span/a/span</value>
      <webElementGuid>be14a8dd-3c52-4ad5-ab83-e16d1d71c9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                MinesSweeper_Java
              ' or . = '
                MinesSweeper_Java
              ')]</value>
      <webElementGuid>06557f74-2c9c-4c0d-afb6-f7f16d087674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
