<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Electronic-Voting-App-Blockchain</name>
   <tag></tag>
   <elementGuidId>8715cb96-b09e-4e6e-af12-cf7c7f70d414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='repo-title-component']/strong/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.d-block.overflow-x-hidden.color-fg-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f30bd388-f420-463d-83e2-bcad3102b637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>#repo-content-pjax-container</value>
      <webElementGuid>67819402-6c13-4718-a9b9-949a8a55405e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-turbo-frame</name>
      <type>Main</type>
      <value>repo-content-turbo-frame</value>
      <webElementGuid>91262f5d-d40a-4a2f-9564-8af1102569e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block overflow-x-hidden color-fg-default</value>
      <webElementGuid>ba6cd497-99e9-4e3b-a3c7-1dca7c00e9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/galik1999/Electronic-Voting-App-Blockchain</value>
      <webElementGuid>2a97fc6f-58a1-40ef-b20d-849a614f5489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Electronic-Voting-App-Blockchain</value>
      <webElementGuid>f6c4ad9b-eff1-4dc6-962a-f4d92591332f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repo-title-component&quot;)/strong[@class=&quot;mr-2 flex-self-stretch d-none d-md-block no-wrap overflow-x-hidden&quot;]/a[@class=&quot;d-block overflow-x-hidden color-fg-default&quot;]</value>
      <webElementGuid>524b0fcd-cf9a-495d-8ac8-89e625f4b331</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repo-title-component']/strong/a</value>
      <webElementGuid>8a5bdda0-98e9-4d0e-b7f1-768558f36574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Electronic-Voting-App-Blockchain')]</value>
      <webElementGuid>339aad81-5d3a-4c76-aadf-20c2a9704b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reload'])[3]/following::a[1]</value>
      <webElementGuid>8bf6bebf-0270-4aca-87f8-d52f5f7c63d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/preceding::a[1]</value>
      <webElementGuid>8cf6df2e-5d63-478b-b297-a75642e71585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/galik1999/Electronic-Voting-App-Blockchain')])[19]</value>
      <webElementGuid>b2484b19-2247-4d91-a5a5-f8171bd03427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong/a</value>
      <webElementGuid>7bb8573d-2e01-4165-8821-4721cb72e195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/galik1999/Electronic-Voting-App-Blockchain' and (text() = 'Electronic-Voting-App-Blockchain' or . = 'Electronic-Voting-App-Blockchain')]</value>
      <webElementGuid>1208b7b4-5941-4cce-877f-281ff3efeec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
