<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Download ZIP</name>
   <tag></tag>
   <elementGuidId>76a5ae85-5582-4ce3-9796-a30096479adb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=':rv:--label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7f93ee5-58a4-4552-a194-0d81238e01c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rv:--label</value>
      <webElementGuid>3d6dc0a8-7eff-4a90-8d8e-51a0e9abba76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Box-sc-g0xbh4-0 jGCjmr</value>
      <webElementGuid>3851ff2a-27d7-4abe-a5f3-c52daa9371f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download ZIP</value>
      <webElementGuid>6d9fc74f-3297-4fe4-a274-4e3e1fea6569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rv:--label&quot;)</value>
      <webElementGuid>a61e6629-0ca3-4277-b4d0-2f0162131012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id=':rv:--label']</value>
      <webElementGuid>b4d2cf75-fb4f-4287-8923-bde81b881b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id=':rv:']/div/span</value>
      <webElementGuid>d1ec8dbb-e7f3-4322-a107-d046813a4efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open with Visual Studio'])[1]/following::span[2]</value>
      <webElementGuid>1a57d730-bce8-4ff3-9d21-7861bd22771a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open with GitHub Desktop'])[1]/following::span[3]</value>
      <webElementGuid>3b254fb2-4391-453f-97f7-a1b826515d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download ZIP']/parent::*</value>
      <webElementGuid>63e7900c-3546-430d-8948-82ab9a21fd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span</value>
      <webElementGuid>6a3d857d-9605-49ca-895d-c4a6649ccc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = ':rv:--label' and (text() = 'Download ZIP' or . = 'Download ZIP')]</value>
      <webElementGuid>494c0f35-ea9a-4511-9f3e-338e2a39d2b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
