<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Code</name>
   <tag></tag>
   <elementGuidId>4167750e-c1cf-458f-af4f-3e64b0d389d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=':R55ab:']/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27325844-31e4-4689-87dd-646ac19913ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07010da8-537d-4eaf-be67-e8406bf78f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>cae14288-2eeb-4cfd-9946-94d50e06cc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:R55ab:&quot;)/span[@class=&quot;Box-sc-g0xbh4-0 kkrdEu&quot;]/span[2]</value>
      <webElementGuid>ad398672-db47-40f9-8bf5-e55cc44ed113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id=':R55ab:']/span/span[2]</value>
      <webElementGuid>994571a0-f0ef-4f14-b341-9ab39a65b679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add file'])[3]/following::span[4]</value>
      <webElementGuid>6cbdc742-57de-4542-a034-a2938230c566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add file'])[2]/following::span[6]</value>
      <webElementGuid>7038c1d7-32fd-4806-b606-58ff88c42557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folders and files'])[1]/preceding::span[2]</value>
      <webElementGuid>44e6353d-c7d9-448e-bf9a-8ab0ec1cb5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::span[2]</value>
      <webElementGuid>f20892ac-507c-468c-8ccd-2759c5ead35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button/span/span[2]</value>
      <webElementGuid>e4b0410d-783f-4a7b-88b8-101b759b9e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Code' or . = 'Code')]</value>
      <webElementGuid>e4c1d77d-fbb3-40e2-9599-e20e0f2dc7d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
